classWeight: 0.8
epochs: 400
updateClip: 0.005
model_name: 'stgcn'
data_path: 'train_data_joint.npy'
label_path: 'train_label.pkl'
num_frame_path: 'train_num_frame.npy'
save_path: '...'
batch_size: 16
hookstatus: True
